version: '3.8'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn library.wsgi:application --bind 52.47.135.217:8000
    ports:
     - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:10
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./.env.prod.db
  # nginx:
  #   build: ./nginx
  #   ports:
  #     - 1337:80
  #   volumes:
  #     - static_volume:/home/app/web/staticfiles
  #   depends_on:
  #     - web

volumes:
  postgres_data:
  # static_volume:
      






 