version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app 
    command: gunicorn library.wsgi:application --bind 0.0.0.0:80
    ports:
     - 80:80
    env_file:
      - ./.env.prod
    depends_on:
      - dj_db
  dj_db:
    container_name: dj_db
    image: postgres:10
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./.env.prod.db
volumes:
  postgres_data:
    