version: '3.8'

services:
  web:
    build: ./
    command: gunicorn library.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    container_name: db
    image: postgres:10
    restart: always
    env_file:
    - ./.env.dev
    volumes:
      - dj_postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=django_jenkins
volumes:
  dj_postgres_data:
      






# version: '3.7'

# services:
#   dj_web:
#     build: .
#     restart: always
#     command: python3 /danil/django/test/manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/danil/django/test
#     ports:
#       - 8000:8000
#     env_file:
#       - ./.env.dev
#     depends_on:
#       - db
#   db:
#     image: postgres:10.18
#     restart: always
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
      

# volumes:
#   postgres_data: